name: Deploy to Release on PR

on:
  pull_request:
    branches: [ "be/production", "be/develop" ]
    types: [ opened, synchronize, reopened ]

env:
  TZ: Asia/Seoul

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: |
      github.event.pull_request.base.ref == 'be/develop' ||
      (github.event.pull_request.base.ref == 'be/production' && github.event.pull_request.head.ref == 'be/develop')
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true

      - name: 서브모듈 최신화
        run: |
          git submodule update --remote

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 설정
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Gradle Wrapper로 빌드 및 테스트 실행
        run: ./gradlew clean test
        working-directory: ./backend

      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: backend/build/reports/tests/test/
